services:
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    depends_on:
      - php
  php:
    build:
      context: .
      target: symfony_php
    depends_on:
      - database
    volumes:
      - ./var:/app/var:rw
      - ./public:/app/public
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION:-18}&charset=${POSTGRES_CHARSET:-utf8}

  database:
    image: postgres:18
    hostname: postgres
    volumes:
      - ./.data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
