version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8081:80
    volumes:
      - ./docker/nginx/conf.d/nginx.${APP_ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
  php:
    build:
      context: .
      target: symfony_php
    volumes:
      - ./var:/app/var:rw
    env_file:
      - .env.local
  database:
    image: postgres:latest
    hostname: postgres
    volumes:
    - ./.data/data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    env_file:
      - .env.local
